openapi: 3.0.0
info:
  title: Market Risk Demo
  description: >-
    Demonstration for finding the histogram for several interest rate sensitive
    assets.
  version: '1'
servers:
  - url: 'https://4mf1valfp4.execute-api.us-east-1.amazonaws.com/prd'
    description: Production server
paths:
  /v1/market/histogram/bond:
    post:
      summary: Computes the histogram for bond prices
      description: Computes the histogram for bond prices
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: &ref_0
                type: object
              example: &ref_1
                5.0000-5.5000: 10
                5.5000-6.0000: 5
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: &ref_2
                type: object
                properties:
                  err:
                    type: string
                required:
                  - err
                additionalProperties: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                t:
                  type: integer
                  example: 10
                  description: Simulate to (days)
                r0:
                  type: number
                  example: 0.04
                  description: Current short rate
                a:
                  type: number
                  example: 0.3
                  description: Mean reversion
                b:
                  type: number
                  example: 0.05
                  description: Long run average rate
                sigma:
                  type: number
                  example: 0.05
                  description: Volatility of rate
                maturity:
                  type: number
                  example: 1
                  description: Bond maturity (years)
              required:
                - t
                - r0
                - a
                - b
                - sigma
                - maturity
              type: object
  /v1/market/histogram/edf:
    post:
      summary: Computes the histogram for Euro Dollar Future prices
      description: Computes the histogram for Euro Dollar Future prices
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                t:
                  type: integer
                  example: 10
                  description: Simulate to (days)
                r0:
                  type: number
                  example: 0.04
                  description: Current short rate
                a:
                  type: number
                  example: 0.3
                  description: Mean reversion
                b:
                  type: number
                  example: 0.05
                  description: Long run average rate
                sigma:
                  type: number
                  example: 0.05
                  description: Volatility of rate
                maturity:
                  type: number
                  example: 1
                  description: EDF maturity (years)
                tenor:
                  type: number
                  example: 0.25
                  description: Floating tenor
              required:
                - t
                - r0
                - a
                - b
                - sigma
                - maturity
                - tenor
              type: object
  /v1/market/histogram/bondcall:
    post:
      summary: Computes the histogram for call options on zero-coupon bonds
      description: Computes the histogram for call options on zero-coupon bonds
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema: &ref_3
              additionalProperties: false
              properties:
                t:
                  type: integer
                  example: 10
                  description: Simulate to (days)
                r0:
                  type: number
                  example: 0.04
                  description: Current short rate
                a:
                  type: number
                  example: 0.3
                  description: Mean reversion
                b:
                  type: number
                  example: 0.05
                  description: Long run average rate
                sigma:
                  type: number
                  example: 0.05
                  description: Volatility of rate
                maturity:
                  type: number
                  example: 1
                  description: Option maturity  (years)
                underlyingMaturity:
                  type: number
                  example: 1.25
                  description: Maturity of underlying bond (years)
                strike:
                  type: number
                  example: 0.97
                  description: Strike
              required:
                - t
                - r0
                - a
                - b
                - sigma
                - maturity
                - underlyingMaturity
                - strike
              type: object
  /v1/market/histogram/bondput:
    post:
      summary: Computes the histogram for put options on zero-coupon bonds
      description: Computes the histogram for put options on zero-coupon bonds
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema: *ref_3
  /v1/market/histogram/caplet:
    post:
      summary: Computes the histogram for caplets
      description: Computes the histogram for caplets
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                t:
                  type: integer
                  example: 10
                  description: Simulate to (days)
                r0:
                  type: number
                  example: 0.04
                  description: Current short rate
                a:
                  type: number
                  example: 0.3
                  description: Mean reversion
                b:
                  type: number
                  example: 0.05
                  description: Long run average rate
                sigma:
                  type: number
                  example: 0.05
                  description: Volatility of rate
                maturity:
                  type: number
                  example: 1
                  description: Option maturity (years)
                tenor:
                  type: number
                  example: 0.25
                  description: Floating tenor
                strike:
                  type: number
                  example: 0.02
                  description: Strike
              required:
                - t
                - r0
                - a
                - b
                - sigma
                - maturity
                - tenor
                - strike
              type: object
  /v1/market/histogram/swap:
    post:
      summary: Computes the histogram for swaps
      description: Computes the histogram for swaps
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                t:
                  type: integer
                  example: 10
                  description: Simulate to (days)
                r0:
                  type: number
                  example: 0.04
                  description: Current short rate
                a:
                  type: number
                  example: 0.3
                  description: Mean reversion
                b:
                  type: number
                  example: 0.05
                  description: Long run average rate
                sigma:
                  type: number
                  example: 0.05
                  description: Volatility of rate
                maturity:
                  type: number
                  example: 1
                  description: Swap maturity (years)
                tenor:
                  type: number
                  example: 0.25
                  description: Floating tenor
                swapRate:
                  type: number
                  example: 0.02
                  description: Swap rate
              required:
                - t
                - r0
                - a
                - b
                - sigma
                - maturity
                - tenor
                - swapRate
              type: object
  /v1/market/histogram/swaption:
    post:
      summary: Computes the histogram for European payer swaptions
      description: Computes the histogram for European payer swaptions
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema: &ref_4
              additionalProperties: false
              properties:
                t:
                  type: integer
                  example: 10
                  description: Simulate to (days)
                r0:
                  type: number
                  example: 0.04
                  description: Current short rate
                a:
                  type: number
                  example: 0.3
                  description: Mean reversion
                b:
                  type: number
                  example: 0.05
                  description: Long run average rate
                sigma:
                  type: number
                  example: 0.05
                  description: Volatility of rate
                maturity:
                  type: number
                  example: 1
                  description: Swap maturity (years)
                tenor:
                  type: number
                  example: 0.25
                  description: Floating tenor
                swapTenor:
                  type: number
                  example: 5
                  description: Swap tenor (years)
                swapRate:
                  type: number
                  example: 0.02
                  description: Swap rate
              required:
                - t
                - r0
                - a
                - b
                - sigma
                - maturity
                - tenor
                - swapTenor
                - swapRate
              type: object
  /v1/market/histogram/americanswaption:
    post:
      summary: Computes the histogram for American payer swaptions
      description: Computes the histogram for American payer swaptions
      responses:
        '200':
          description: Histogram
          content:
            application/json:
              schema: *ref_0
              example: *ref_1
        '400':
          description: Error for incorrect request
          content:
            application/json:
              schema: *ref_2
      requestBody:
        required: true
        content:
          application/json:
            schema: *ref_4
